/* Generated By:JavaCC: Do not edit this line. OPathConstants.java */
package me.hch.text;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OPathConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int IDENTIFIER = 9;
  /** RegularExpression Id. */
  int KEY = 10;
  /** RegularExpression Id. */
  int VAL = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<LETTER>",
    "<DIGIT>",
    "<AND>",
    "<OR>",
    "<IDENTIFIER>",
    "<KEY>",
    "<VAL>",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
  };

}
